//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectXDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchCourseFacultyMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchCourseFacultyMapping()
        {
            this.Graders = new HashSet<Grader>();
        }
    
        public int BatchId { get; set; }
        public string CourseId { get; set; }
        public string FacultyId { get; set; }
        public int BCFId { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grader> Graders { get; set; }
    }
}
