//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectXDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grader
    {
        public int BCFId { get; set; }
        public int PSNO { get; set; }
        public double Score { get; set; }
        public int GId { get; set; }
    
        public virtual BatchCourseFacultyMapping BatchCourseFacultyMapping { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
