//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectXDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectDataEntities : DbContext
    {
        public ProjectDataEntities()
            : base("name=ProjectDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<BatchCourseFacultyMapping> BatchCourseFacultyMappings { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<DeliveryModel> DeliveryModels { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Grader> Graders { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<FacultyCourseMapping> FacultyCourseMappings { get; set; }
    
        [DbFunction("ProjectDataEntities", "ufnBottomFiveScoreByCId")]
        public virtual IQueryable<ufnBottomFiveScoreByCId_Result> ufnBottomFiveScoreByCId(string courseId)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnBottomFiveScoreByCId_Result>("[ProjectDataEntities].[ufnBottomFiveScoreByCId](@courseId)", courseIdParameter);
        }
    
        [DbFunction("ProjectDataEntities", "ufnGetCourseScoreByFId")]
        public virtual IQueryable<ufnGetCourseScoreByFId_Result> ufnGetCourseScoreByFId(string facultyId)
        {
            var facultyIdParameter = facultyId != null ?
                new ObjectParameter("facultyId", facultyId) :
                new ObjectParameter("facultyId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetCourseScoreByFId_Result>("[ProjectDataEntities].[ufnGetCourseScoreByFId](@facultyId)", facultyIdParameter);
        }
    
        [DbFunction("ProjectDataEntities", "ufnGetFacultyByCId")]
        public virtual IQueryable<ufnGetFacultyByCId_Result> ufnGetFacultyByCId(string courseId)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetFacultyByCId_Result>("[ProjectDataEntities].[ufnGetFacultyByCId](@courseId)", courseIdParameter);
        }
    
        [DbFunction("ProjectDataEntities", "ufnGetParticipantsByCId")]
        public virtual IQueryable<ufnGetParticipantsByCId_Result> ufnGetParticipantsByCId(string cId)
        {
            var cIdParameter = cId != null ?
                new ObjectParameter("cId", cId) :
                new ObjectParameter("cId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetParticipantsByCId_Result>("[ProjectDataEntities].[ufnGetParticipantsByCId](@cId)", cIdParameter);
        }
    
        [DbFunction("ProjectDataEntities", "ufnTopFiveScoreByCId")]
        public virtual IQueryable<ufnTopFiveScoreByCId_Result> ufnTopFiveScoreByCId(string courseId)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnTopFiveScoreByCId_Result>("[ProjectDataEntities].[ufnTopFiveScoreByCId](@courseId)", courseIdParameter);
        }
    
        public virtual int uspAddCourses(string courseId, string courseTitle, Nullable<int> courseDuration, string courseMode)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            var courseTitleParameter = courseTitle != null ?
                new ObjectParameter("CourseTitle", courseTitle) :
                new ObjectParameter("CourseTitle", typeof(string));
    
            var courseDurationParameter = courseDuration.HasValue ?
                new ObjectParameter("CourseDuration", courseDuration) :
                new ObjectParameter("CourseDuration", typeof(int));
    
            var courseModeParameter = courseMode != null ?
                new ObjectParameter("CourseMode", courseMode) :
                new ObjectParameter("CourseMode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspAddCourses", courseIdParameter, courseTitleParameter, courseDurationParameter, courseModeParameter);
        }
    
        public virtual ObjectResult<string> uspBatchCourseFacultyMapping(string courseId, string facultyId, Nullable<int> batchId)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            var facultyIdParameter = facultyId != null ?
                new ObjectParameter("FacultyId", facultyId) :
                new ObjectParameter("FacultyId", typeof(string));
    
            var batchIdParameter = batchId.HasValue ?
                new ObjectParameter("BatchId", batchId) :
                new ObjectParameter("BatchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspBatchCourseFacultyMapping", courseIdParameter, facultyIdParameter, batchIdParameter);
        }
    
        public virtual int uspBatchInput(string batchName, Nullable<System.DateTime> startDate, Nullable<int> studentCount, Nullable<int> modelId)
        {
            var batchNameParameter = batchName != null ?
                new ObjectParameter("BatchName", batchName) :
                new ObjectParameter("BatchName", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var studentCountParameter = studentCount.HasValue ?
                new ObjectParameter("StudentCount", studentCount) :
                new ObjectParameter("StudentCount", typeof(int));
    
            var modelIdParameter = modelId.HasValue ?
                new ObjectParameter("ModelId", modelId) :
                new ObjectParameter("ModelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspBatchInput", batchNameParameter, startDateParameter, studentCountParameter, modelIdParameter);
        }
    
        public virtual ObjectResult<string> uspDeleteCourse(string courseId)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspDeleteCourse", courseIdParameter);
        }
    
        public virtual ObjectResult<string> uspDeleteFaculty(string psno)
        {
            var psnoParameter = psno != null ?
                new ObjectParameter("psno", psno) :
                new ObjectParameter("psno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspDeleteFaculty", psnoParameter);
        }
    
        public virtual int uspFacultyAdd(string pSNO, string emailId, string facultyName)
        {
            var pSNOParameter = pSNO != null ?
                new ObjectParameter("PSNO", pSNO) :
                new ObjectParameter("PSNO", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspFacultyAdd", pSNOParameter, emailIdParameter, facultyNameParameter);
        }
    
        public virtual int uspGraderInput(Nullable<int> bCFId, Nullable<int> pSNO, Nullable<double> score)
        {
            var bCFIdParameter = bCFId.HasValue ?
                new ObjectParameter("BCFId", bCFId) :
                new ObjectParameter("BCFId", typeof(int));
    
            var pSNOParameter = pSNO.HasValue ?
                new ObjectParameter("PSNO", pSNO) :
                new ObjectParameter("PSNO", typeof(int));
    
            var scoreParameter = score.HasValue ?
                new ObjectParameter("Score", score) :
                new ObjectParameter("Score", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGraderInput", bCFIdParameter, pSNOParameter, scoreParameter);
        }
    
        public virtual ObjectResult<string> uspMapCourseModel(Nullable<int> modelId, string courseId)
        {
            var modelIdParameter = modelId.HasValue ?
                new ObjectParameter("ModelId", modelId) :
                new ObjectParameter("ModelId", typeof(int));
    
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspMapCourseModel", modelIdParameter, courseIdParameter);
        }
    
        public virtual ObjectResult<string> uspMapDelivaryModel(string modelName)
        {
            var modelNameParameter = modelName != null ?
                new ObjectParameter("ModelName", modelName) :
                new ObjectParameter("ModelName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspMapDelivaryModel", modelNameParameter);
        }
    
        public virtual ObjectResult<string> uspMapFacultyCourse(string courseId, string pSNO, string primaryFaculty)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(string));
    
            var pSNOParameter = pSNO != null ?
                new ObjectParameter("PSNO", pSNO) :
                new ObjectParameter("PSNO", typeof(string));
    
            var primaryFacultyParameter = primaryFaculty != null ?
                new ObjectParameter("PrimaryFaculty", primaryFaculty) :
                new ObjectParameter("PrimaryFaculty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspMapFacultyCourse", courseIdParameter, pSNOParameter, primaryFacultyParameter);
        }
    
        public virtual ObjectResult<string> uspParticipantsInput(string participantsName, string participantsEmail)
        {
            var participantsNameParameter = participantsName != null ?
                new ObjectParameter("ParticipantsName", participantsName) :
                new ObjectParameter("ParticipantsName", typeof(string));
    
            var participantsEmailParameter = participantsEmail != null ?
                new ObjectParameter("ParticipantsEmail", participantsEmail) :
                new ObjectParameter("ParticipantsEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspParticipantsInput", participantsNameParameter, participantsEmailParameter);
        }
    
        public virtual ObjectResult<string> uspPBMappingInput(Nullable<int> pSNo, Nullable<int> batchId)
        {
            var pSNoParameter = pSNo.HasValue ?
                new ObjectParameter("PSNo", pSNo) :
                new ObjectParameter("PSNo", typeof(int));
    
            var batchIdParameter = batchId.HasValue ?
                new ObjectParameter("BatchId", batchId) :
                new ObjectParameter("BatchId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspPBMappingInput", pSNoParameter, batchIdParameter);
        }
    
        public virtual int uspUpdateCourse(string courseId, string courseTitle, Nullable<int> courseDuration, string courseMode, byte[] curriculum)
        {
            var courseIdParameter = courseId != null ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(string));
    
            var courseTitleParameter = courseTitle != null ?
                new ObjectParameter("courseTitle", courseTitle) :
                new ObjectParameter("courseTitle", typeof(string));
    
            var courseDurationParameter = courseDuration.HasValue ?
                new ObjectParameter("courseDuration", courseDuration) :
                new ObjectParameter("courseDuration", typeof(int));
    
            var courseModeParameter = courseMode != null ?
                new ObjectParameter("courseMode", courseMode) :
                new ObjectParameter("courseMode", typeof(string));
    
            var curriculumParameter = curriculum != null ?
                new ObjectParameter("curriculum", curriculum) :
                new ObjectParameter("curriculum", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateCourse", courseIdParameter, courseTitleParameter, courseDurationParameter, courseModeParameter, curriculumParameter);
        }
    
        public virtual ObjectResult<string> uspUpdateFaculties(string psno, string emailId, string facultyName)
        {
            var psnoParameter = psno != null ?
                new ObjectParameter("psno", psno) :
                new ObjectParameter("psno", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("emailId", emailId) :
                new ObjectParameter("emailId", typeof(string));
    
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("uspUpdateFaculties", psnoParameter, emailIdParameter, facultyNameParameter);
        }
    }
}
